
name: solariot # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: P2P Energy Transactions Smart Grid Blockchain # 79 char long summary
description: |
  Using P2P Transactions to develop microgrids and exchange clean energy
  using blockchain and distributed ledger technology.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nodejs
    node-engine: 8.1.0
    node-packages: [coinkey,coininfo,express,ethereumjs-vm,express,node-gyp,async,ethereumjs-account,ethereumjs-tx,merkle-patricia-tree,rlp,ethereumjs-util]
